language: python
cache: pip
matrix:
  include:
  - os: osx
    language: generic
  - python: pypy
    arch: amd64
  - python: 2.7
    arch: amd64
  - python: 3.5
    arch: amd64
  - python: 3.6
    arch: amd64
  - python: 3.7
    arch: amd64
  - python: 3.8
    arch: amd64
  - python: 3.9-dev
    arch: amd64
  - python: 2.7
    arch: ppc64le
  - python: 3.5
    arch: ppc64le
  - python: 3.6
    arch: ppc64le
  - python: 3.7
    arch: ppc64le
  - python: 3.8
    arch: ppc64le
  - python: 3.9-dev
    arch: ppc64le

install:
  - scripts/travis.sh pip install --upgrade setuptools
  - scripts/travis.sh pip install --upgrade --requirement=requirements-travis.txt
  - scripts/travis.sh LC_ALL=C pip install .
script:
  - scripts/travis.sh make check
  - scripts/travis.sh make test
after_success:
  - scripts/travis.sh coveralls
branches:
  except:
    - /^[0-9]/
